# FINAL snake.yml - Dark Background Boxes & Colored Snake

name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants permission to write to the repository
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sohamrajput98
          
          # 🐍 The snake itself is now your vibrant "Royal Void" purple
          color_snake: "#C084FC" 
          
          # The contribution dots it eats are your lilac and pink accent colors
          color_dots: "#4CAF50,#66BB6A,#81C784,#A5D6A7"
          
          # 🔲 This line generates a single file named snake.svg
          # AND ensures the background grid/boxes are dark
          outputs: dist/snake.svg?palette=github-dark

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
